###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username":"maideptrai",
    "password":"12345678","identity":"12345678",
    "phone":"12345678",
    "name":"Nguyễn Tấn Mãi"
}
###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username":"maideptrai",
    "password":"12345678"
}